#!/bin/bash

workdir=$PWD

## depends ##

#https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git
# clone or Update git
if [ ! -d "$workdir/iso-profiles" ]
then
    git clone https://gitlab.manjaro.org/profiles-and-settings/iso-profiles.git
else
    cd $workdir/iso-profiles
    git pull
    cd $workdir
fi

#remove old profile
if [ -d "$workdir/iso-profiles/community/biglinux" ]; then
    rm -r $workdir/iso-profiles/community/biglinux
fi

## create profile biglinux ##
mkdir -p $workdir/iso-profiles/community/biglinux

#files
cp $workdir/iso-profiles-biglinux/profile.conf  $workdir/iso-profiles/community/biglinux/
cp $workdir/iso-profiles-biglinux/pacman-default.conf  $workdir/iso-profiles/community/biglinux/
cp $workdir/iso-profiles-biglinux/user-repos.conf  $workdir/iso-profiles/community/biglinux/
#dirs
cp -r $workdir/iso-profiles-biglinux/desktop-overlay/  $workdir/iso-profiles/community/biglinux/
cp -r $workdir/iso-profiles-biglinux/live-overlay/  $workdir/iso-profiles/community/biglinux/

# Remove Mhwd
if [ -e "$workdir/iso-profiles-biglinux/Mhwd-remove" ]; then
    grep -v -f $workdir/iso-profiles-biglinux/Mhwd-remove  $workdir/iso-profiles/shared/Packages-Mhwd  >  $workdir/iso-profiles/community/biglinux/Packages-Mhwd
else
    echo "ERROR"
    exit 1
fi

# Remove Root
if [ -e "$workdir/iso-profiles-biglinux/Root-remove" ]; then
    grep -v -f $workdir/iso-profiles-biglinux/Root-remove  $workdir/iso-profiles/shared/Packages-Root  >  $workdir/iso-profiles/community/biglinux/Packages-Root
else
    echo "ERROR"
    exit 1
fi

# Remove Live
if [ -e "$workdir/iso-profiles-biglinux/Live-remove" ]; then
    grep -v -f $workdir/iso-profiles-biglinux/Live-remove  $workdir/iso-profiles/shared/Packages-Live  >  $workdir/iso-profiles/community/biglinux/Packages-Live
else
    echo "ERROR"
    exit 1
fi

# Remove Desktop
if [ -e "$workdir/iso-profiles-biglinux/Desktop-remove" ]; then
    grep -v -f $workdir/iso-profiles-biglinux/Desktop-remove  $workdir/iso-profiles/shared/Packages-Desktop  >  $workdir/iso-profiles/community/biglinux/Packages-Desktop
else
    echo "ERROR"
    exit 1
fi

# Add Mhwd
if [ -e "$workdir/iso-profiles-biglinux/Mhwd-add" ]; then
    cat $workdir/iso-profiles-biglinux/Mhwd-add  >>  $workdir/iso-profiles/community/biglinux/Packages-Mhwd
else
    echo "ERROR"
    exit 1
fi


# Add Root
if [ -e "$workdir/iso-profiles-biglinux/Root-add" ]; then
    cat $workdir/iso-profiles-biglinux/Root-add  >>  $workdir/iso-profiles/community/biglinux/Packages-Root
else
    echo "ERROR"
    exit 1
fi

# # use mesa-amber ?
# if [ "$3" = "amber" ]; then
#     echo 'mesa-amber
# lib32-mesa-amber' >> iso-profiles/community/biglinux/Packages-Root
# fi

# Add Live
if [ -e "$workdir/iso-profiles-biglinux/Live-add" ]; then
#     echo '' >> iso-profiles/community/biglinux/Packages-Live
    cat $workdir/iso-profiles-biglinux/Live-add  >>  $workdir/iso-profiles/community/biglinux/Packages-Live
else
    echo "ERROR"
    exit 1
fi

# Add Desktop
if [ -e "$workdir/iso-profiles-biglinux/Desktop-add" ]; then
    cat  $workdir/iso-profiles-biglinux/Desktop-add  >  $workdir/iso-profiles/community/biglinux/Packages-Desktop
else
    echo "ERROR"
    exit 1
fi

# Add some things from Packages-Desktop
sed -n '/## Printing/,/^$/p'  $workdir/iso-profiles/manjaro/kde/Packages-Desktop  >>  $workdir/iso-profiles/community/biglinux/Packages-Desktop
sed -n '/## Xorg Server and Graphics/,/^$/p'  $workdir/iso-profiles/manjaro/kde/Packages-Desktop  >>  $workdir/iso-profiles/community/biglinux/Packages-Desktop
sed -n '/## Xorg Input Drivers/,/^$/p'  $workdir/iso-profiles/manjaro/kde/Packages-Desktop  >>  $workdir/iso-profiles/community/biglinux/Packages-Desktop
sed -n '/## Misc/,/^$/p'  $workdir/iso-profiles/manjaro/kde/Packages-Desktop  >>  $workdir/iso-profiles/community/biglinux/Packages-Desktop
sed -i 's|xf86-input-void||g'  $workdir/iso-profiles/community/biglinux/Packages-Desktop

